language: python
dist: trusty
sudo: false

matrix:
  include:
    - os: linux
      language: generic
      env:
      - PYTHON_VERSION=3.7.1
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=3.7.1
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH

before_install:
  - bash .ci/deps.${TRAVIS_OS_NAME}.sh

before_script:
  - bash .ci/pre.${TRAVIS_OS_NAME}.sh

install:
  - pip install -U pip setuptools
  - pip install -r requirements.txt

script:
  - pytest

after_success:
  - coveralls
