language: python

sudo: false

matrix:
  include:
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      dist: xenial
      python: 3.7
    - os: linux
      python: pypy3
    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=3.5.6
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=3.6.8
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=3.7.2
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH


before_install:
  - bash .ci/deps.${TRAVIS_OS_NAME}.sh

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

before_script:
  - bash .ci/pre.${TRAVIS_OS_NAME}.sh

script:
  - make test

after_success:
  - coveralls
