version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  lint-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Lint
          command: make lint
      - run:
          command: make test
          name: Test

workflows:
  main:
    jobs:
      - lint-and-test
