version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  lint-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: make lint
          name: Lint
      - run:
          command: make test
          name: Test

workflows:
  main:
    jobs:
      - lint-and-test
